package game;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Miguel Antonio
 */
public class ThreeX extends javax.swing.JFrame {

    boolean estado = true;
    String siguienteJuego = "O";
    String turno = "";
    JLabel lbs[] = new JLabel[9];
    int vs[][] = {
        {1,2,3},
        {4,5,6},
        {7,8,9},
        {1,4,7},
        {2,5,8},  
        {3,6,9},
        {1,5,9},
        {3,5,7}
    };
    
    public ThreeX() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbs[0] = jLabel01;
        lbs[1] = jLabel02;
        lbs[2] = jLabel03;
        lbs[3] = jLabel04;
        lbs[4] = jLabel05;
        lbs[5] = jLabel06;
        lbs[6] = jLabel07;
        lbs[7] = jLabel08;
        lbs[8] = jLabel09;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel03 = new javax.swing.JLabel();
        jLabel01 = new javax.swing.JLabel();
        jLabel08 = new javax.swing.JLabel();
        jLabel07 = new javax.swing.JLabel();
        jLabel06 = new javax.swing.JLabel();
        jLabel04 = new javax.swing.JLabel();
        jLabel05 = new javax.swing.JLabel();
        jLabel09 = new javax.swing.JLabel();
        jLabel02 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbTurno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbPuntajeX = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbPuntajeO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego 3 en raya");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jLabel03.setBackground(new java.awt.Color(255, 255, 255));
        jLabel03.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel03.setForeground(new java.awt.Color(0, 0, 0));
        jLabel03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel03.setOpaque(true);
        jLabel03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel03MousePressed(evt);
            }
        });

        jLabel01.setBackground(new java.awt.Color(255, 255, 255));
        jLabel01.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel01.setForeground(new java.awt.Color(0, 0, 0));
        jLabel01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel01.setOpaque(true);
        jLabel01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel01MousePressed(evt);
            }
        });

        jLabel08.setBackground(new java.awt.Color(255, 255, 255));
        jLabel08.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel08.setForeground(new java.awt.Color(0, 0, 0));
        jLabel08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel08.setOpaque(true);
        jLabel08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel08MousePressed(evt);
            }
        });

        jLabel07.setBackground(new java.awt.Color(255, 255, 255));
        jLabel07.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel07.setForeground(new java.awt.Color(0, 0, 0));
        jLabel07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel07.setOpaque(true);
        jLabel07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel07MousePressed(evt);
            }
        });

        jLabel06.setBackground(new java.awt.Color(255, 255, 255));
        jLabel06.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel06.setForeground(new java.awt.Color(0, 0, 0));
        jLabel06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel06.setOpaque(true);
        jLabel06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel06MousePressed(evt);
            }
        });

        jLabel04.setBackground(new java.awt.Color(255, 255, 255));
        jLabel04.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel04.setForeground(new java.awt.Color(0, 0, 0));
        jLabel04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel04.setOpaque(true);
        jLabel04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel04MousePressed(evt);
            }
        });

        jLabel05.setBackground(new java.awt.Color(255, 255, 255));
        jLabel05.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel05.setForeground(new java.awt.Color(0, 0, 0));
        jLabel05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel05.setOpaque(true);
        jLabel05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel05MousePressed(evt);
            }
        });

        jLabel09.setBackground(new java.awt.Color(255, 255, 255));
        jLabel09.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel09.setForeground(new java.awt.Color(0, 0, 0));
        jLabel09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel09.setOpaque(true);
        jLabel09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel09MousePressed(evt);
            }
        });

        jLabel02.setBackground(new java.awt.Color(255, 255, 255));
        jLabel02.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel02.setForeground(new java.awt.Color(0, 0, 0));
        jLabel02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel02.setOpaque(true);
        jLabel02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel02MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel04, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel07, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel08, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel05, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel02, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel09, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(jLabel06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel01, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 309, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel03, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel02, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel05, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel06, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel08, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel07, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel09, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel04, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel01, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 219, Short.MAX_VALUE)))
        );

        jButton1.setText("Reiniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbTurno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTurno.setForeground(new java.awt.Color(0, 0, 0));
        lbTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTurno.setText("Turno de X");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("O =");
        jLabel1.setToolTipText("");

        lbPuntajeX.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPuntajeX.setForeground(new java.awt.Color(0, 0, 0));
        lbPuntajeX.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPuntajeX.setText("0");
        lbPuntajeX.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X =");
        jLabel3.setToolTipText("");

        lbPuntajeO.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPuntajeO.setForeground(new java.awt.Color(0, 0, 0));
        lbPuntajeO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPuntajeO.setText("0");
        lbPuntajeO.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lbPuntajeX, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPuntajeO, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(499, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbTurno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPuntajeX, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPuntajeO, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(438, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel01MousePressed
        presionar(1);
    }//GEN-LAST:event_jLabel01MousePressed

    private void jLabel02MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel02MousePressed
        presionar(2);
    }//GEN-LAST:event_jLabel02MousePressed

    private void jLabel03MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel03MousePressed
        presionar(3);
    }//GEN-LAST:event_jLabel03MousePressed

    private void jLabel04MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel04MousePressed
        presionar(4);
    }//GEN-LAST:event_jLabel04MousePressed

    private void jLabel05MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel05MousePressed
        presionar(5);
    }//GEN-LAST:event_jLabel05MousePressed

    private void jLabel06MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel06MousePressed
        presionar(6);
    }//GEN-LAST:event_jLabel06MousePressed

    private void jLabel07MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel07MousePressed
        presionar(7);
    }//GEN-LAST:event_jLabel07MousePressed

    private void jLabel08MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel08MousePressed
        presionar(8);
    }//GEN-LAST:event_jLabel08MousePressed

    private void jLabel09MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel09MousePressed
        presionar(9);
    }//GEN-LAST:event_jLabel09MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (int i = 0; i < lbs.length; i++) {
            lbs[i].setText("");
            lbs[i].setBackground(Color.WHITE);
        }
        
        turno = siguienteJuego;
        if(siguienteJuego.equals("O")){
            siguienteJuego = "X";
            
        }else{
            
            siguienteJuego = "O";
        }
        
        lbTurno.setText("Turno de "+turno);
        estado = true;
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void presionar(int casilla){
        if(lbs[casilla-1].getText().equals("") && estado){
        lbs[casilla-1].setText(turno);  
        cambiarTurno();
        comprobarGanador();
        }
        
    }
    
    public void cambiarTurno(){
        
        if(turno.equals("X")){
            turno = "O";
        }else{
            turno = "X";
        }
        
        lbTurno.setText("Turno de "+turno);
    }
    
    public void comprobarGanador(){
        
        for (int i = 0; i < vs.length; i++) {
            if(lbs[vs[i][0]-1].getText().equals("X")&&
                    lbs[vs[i][1]-1].getText().equals("X")&&
                    lbs[vs[i][2]-1].getText().equals("X")){
                
                lbs[vs[i][0]-1].setBackground(Color.GREEN);
                lbs[vs[i][1]-1].setBackground(Color.GREEN);
                lbs[vs[i][2]-1].setBackground(Color.GREEN);
                lbPuntajeX.setText(Integer.toString(Integer.parseInt(lbPuntajeX.getText())+1));
                lbTurno.setText("Ha Ganado X");
                estado = false;
            }
            if(lbs[vs[i][0]-1].getText().equals("O")&&
                    lbs[vs[i][1]-1].getText().equals("O")&&
                    lbs[vs[i][2]-1].getText().equals("O")){
                
                lbs[vs[i][0]-1].setBackground(Color.RED);
                lbs[vs[i][1]-1].setBackground(Color.RED);
                lbs[vs[i][2]-1].setBackground(Color.RED);
                lbPuntajeO.setText(Integer.toString(Integer.parseInt(lbPuntajeO.getText())+1));
                lbTurno.setText("Ha Ganado O");
                estado = false; 
            }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreeX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreeX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreeX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreeX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreeX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel01;
    private javax.swing.JLabel jLabel02;
    private javax.swing.JLabel jLabel03;
    private javax.swing.JLabel jLabel04;
    private javax.swing.JLabel jLabel05;
    private javax.swing.JLabel jLabel06;
    private javax.swing.JLabel jLabel07;
    private javax.swing.JLabel jLabel08;
    private javax.swing.JLabel jLabel09;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbPuntajeO;
    private javax.swing.JLabel lbPuntajeX;
    private javax.swing.JLabel lbTurno;
    // End of variables declaration//GEN-END:variables
}
